### ISSUE TITLE
the restore state fired twice

### ISSUE THREAD

**Issue by salim-lachdhaf** [littlerobots/flutter-native-state#22] opened 2020-11-09 13:36 UTC
thank you for this plugin, in my case after resoting the state the `initState()`, `didChangeDependencies `are called twice, seems the call fired twice , this issue apears only in case of restore state.

Any help please

**Comment by hvisser** [comment] 2020-11-10 17:06
Please provide a sample project and more details. The tree may be rebuilt twice as the state is loaded, this is normal.

**Comment by salim-lachdhaf** [comment] 2020-11-30 17:47
finally i get the original problem, in fact, the problem is that the child widgets initState get recalled ! and this caused a lot of problem in my code ... and it's not logic , and the source of problem is adding `navigationKey `or `key `as i mention here
https://github.com/flutter/flutter/issues/71399
is there any solution to bypass the uses of the key ?

**Comment by hvisser** [comment] 2020-11-30 19:06
I don't think so, you need to hold on to the navigator using the key for it to push the initial routes correctly. 

You might in fact need to use a key for the widget that has its init state called twice: the reason that it is called twice is probably because the tree gets rebuilt and Flutter does not consider that widget to be a widget that was in the tree already for some reason. 

This is all speculation without a sample that reproduces the issue, and even so it doesn't sound like the issue is related or caused by the plugin.

**Comment by salim-lachdhaf** [comment] 2020-11-30 19:19
Yes that's correct, it not a plugin issue in itself, for this i asked if there is an alternative solution to resolve or replace globalKey , the time flutter team fix the issue

**Comment by hvisser** [comment] 2020-11-30 20:16
OK, so in that case I'll close this issue, as there's nothing that can be done from the plugin side.

**Closed as completed by hvisser** 2020-11-30 20:16 UTC
